### ISSUE TITLE
Support proper section inheritance

### ISSUE THREAD

**Issue by senekor** [senekor/ec2hx#10]
Currently, the only inheritance scenarios supported are:
- from the global section `[*]` to all others
- among sections that map cleanly to files (`[{*.py,*.rs}]` -> `[*.py]`)
- from a language section to a glob section (`[*.py]` -> `[scripts/**]`)

Notably, there is no inheritance between glob sections, i.e. `[docs/internal/**]` cannot inherit from `[docs/**]`.

A more thorough approach could be to walk the sections backwards and check if _a file that matches the current section also matches this previous section_. It may be a good idea to keep some auxiliary data structure to make walking backwards and matching section globs more efficient.

Also, a glob section produces many synthetic language specifications, but these cannot inherit from later, language-specific sections. The correct behavior would be if
```ini
[scripts/**]
indent_size = 4

[*.py]
indent_style = tab
```
would produce such a synthetic language config:
```toml
[[language]]
name = "ec2hx-glob-lang-scripts-**-python"
indent = { unit = "\t", tab-width = 4 }
file-types = { glob = "scripts/**/*.py" }
```
